<a href="https://colab.research.google.com/github/pi-aire/dataminig_sampling/blob/main/TP_DataMining.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Échantillonnage direct de l'espace des motifs

### BRUNEAU Richard - VASLIN Pierre





In [1]:
import numpy as np
import scipy.special as sps
import math
import matplotlib
import pandas as pd
import random

In [4]:
# Le dataframe
df = pd.read_table("https://bitbucket.org/anesbendimerad/sigibbssamplingcode/raw/6699a50508fe177ee0c00dcc7d8e5390ee53688a/ItemsetDatasets/chess.txt", sep=" ",header=None)
del df[37]
df.head()

0   1   2   3   4   5   6   7   8   9   ...  27  28  29  30  31  32  33  \
0   1   3   5   7   9  11  13  15  17  19  ...  56  58  60  62  64  66  68   
1   1   3   5   7   9  12  13  15  17  19  ...  56  58  60  62  64  66  68   
2   1   3   5   7   9  12  13  16  17  19  ...  56  58  60  62  64  66  68   
3   1   3   5   7   9  11  13  15  17  20  ...  56  58  60  62  64  66  68   
4   1   3   5   7   9  11  13  15  17  19  ...  56  58  60  62  64  66  68   

   34  35  36  
0  70  72  74  
1  70  72  74  
2  70  72  74  
3  70  72  74  
4  70  72  74  

[5 rows x 37 columns]

In [7]:
df = pd.read_fwf("https://bitbucket.org/anesbendimerad/sigibbssamplingcode/raw/6699a50508fe177ee0c00dcc7d8e5390ee53688a/ItemsetDatasets/chess.txt", sep="",header=None)
df

0  1  2  3                                                  4
0     1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 34 36 38 40...
1     1  3  5  7  9 12 13 15 17 19 21 23 25 27 29 31 34 36 38 40...
2     1  3  5  7  9 12 13 16 17 19 21 23 25 27 29 31 34 36 38 40...
3     1  3  5  7  9 11 13 15 17 20 21 23 25 27 29 31 34 36 38 40...
4     1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 34 36 38 40...
...  .. .. .. ..                                                ...
3191  2  4  5  7  9 11 13 16 17 19 21 23 26 27 29 33 34 36 38 40...
3192  2  4  5  7  9 11 13 16 17 19 21 23 26 27 29 33 34 36 38 40...
3193  2  4  5  7  9 11 13 16 17 19 21 23 26 27 29 31 34 36 38 40...
3194  2  4  5  8  9 11 13 16 17 19 21 23 26 27 30 33 35 36 38 40...
3195  2  4  5  8  9 11 13 16 17 19 21 23 26 27 30 31 35 36 38 40...

[3196 rows x 5 columns]

## Question 1

In [2]:
def algoFrequences(df:pd.DataFrame,nb_pattern)-> tuple:
  #R:set = set()
  R = []
  IsInR = set()
  P: dict = dict()
  w = np.zeros(df.shape[0])
  totalW = 0
    
  # set les probas
  for i in range(len(w)):
    size = len(df.iloc[i].dropna())
    w[i] = math.pow(2,size)
    totalW += w[i]
  
  # on selectionne 
  while len(R) < nb_pattern:
    random_row = random.uniform(0,totalW)
    # On cherche la ligne
    row = 0
    v = 0
    for i in range(len(w)):
      if  v > random_row:
        row = i - 1
        break
      v += w[i]
    # On selctionne un motif 
    pattern = np.array(df.iloc[row].dropna())
    random_v = random.randint(1, len(pattern) - 1 )
    for i in range(len(pattern)- random_v):
      pattern = np.delete(pattern, random.randint(0, len(pattern) - 1 ))
    # On ajoute seulement les motifs non présent dans l'ensemble R
    IsInR.add(np.array2string(pattern))
    if len(IsInR) != len(R):
      R.append(pattern)
  return R

In [9]:
algoFrequences(df,10)

[array([1], dtype=object),
 array([3, 7,
        '9 12 14 16 17 19 21 24 25 27 29 32 34 36 39 40 43 44 46 48 51 52 54 56 58 60 62 65 66 68 71 72 74'],
       dtype=object),
 array([3, 7], dtype=object),
 array([1, 7], dtype=object),
 array([3, 5, 7,
        '9 11 14 15 17 19 22 24 25 27 29 32 34 36 38 40 42 45 46 48 50 52 54 56 58 60 62 65 66 69 70 72 74'],
       dtype=object),
 array([7], dtype=object),
 array([2], dtype=object),
 array([3], dtype=object),
 array([5,
        '9 12 14 15 18 20 22 24 25 27 29 32 34 36 39 40 43 44 46 48 50 52 54 56 58 60 62 64 66 68 71 73 74'],
       dtype=object),
 array([2, 3,
        '9 12 13 16 17 19 22 23 25 28 29 31 34 36 38 40 42 44 46 48 50 52 55 56 58 60 62 64 66 69 70 72 75'],
       dtype=object)]

## Question 2

In [3]:
def algoArea(df:pd.DataFrame,nb_pattern)-> tuple:
  R = []
  IsInR = set()
  
  # set les probas
  w = np.zeros(df[0].count())
  totalW = 0
  for i in range(1, len(w)):
    size = len(df.iloc[i].dropna())
    w[i] = size * (2 ** (size - 1))
    totalW += w[i]
  
  # on selectionne 
  while len(R) < nb_pattern:
    # On cherche la ligne
    random_row = random.uniform(0,totalW)
    v, row = 0,0
    for i in range(len(w)):
      if v > random_row:
        row = i - 1
        break
      v += w[i]
      
    # On set les probabilités de k (taille du motif)
    # On souhaite que le sous-ensemble est une taille calculée 
    # proportionnellement avec les tailles des datarecords (ligne) 
    ks = np.zeros(len(df.iloc[row].dropna()))
    totalK = 0
    for i in range(len(ks)):
        ks[i] = sps.binom(len(ks), i + 1)
        totalK += ks[i]
    random_kp = random.uniform(0, totalK)
    # On cherche la ligne
    k, v = 0,0
    for i in range(len(ks)):
      if v > random_kp:
        k = i - 1
        break
      v += ks[i]
    
    pattern = np.array(df.iloc[row])
    for i in range(len(pattern)- k):
      pattern = np.delete(pattern, random.randint(0, len(pattern) - 1 ))
    
    # On ajoute seulement les motifs non présent dans l'ensemble R
    IsInR.add(np.array2string(pattern))
    if len(IsInR) != len(R):
      R.append(pattern)
  return R

In [11]:
algoArea(df,10)

[array([], dtype=object),
 array([5, 7], dtype=object),
 array([2], dtype=object),
 array([1,
        '9 11 13 15 17 19 21 23 25 27 29 31 34 36 39 40 42 44 46 48 51 52 54 56 58 60 62 64 66 68 70 72 74'],
       dtype=object),
 array([3], dtype=object),
 array([5, 8], dtype=object),
 array([3,
        '9 11 13 15 17 19 21 23 25 27 29 31 34 36 39 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70 72 74'],
       dtype=object),
 array([2,
        '9 12 14 16 18 20 22 23 25 28 29 31 34 36 38 40 42 44 46 48 50 52 55 56 58 60 62 64 66 68 70 72 74'],
       dtype=object),
 array([1], dtype=object),
 array(['9 11 14 15 17 20 21 23 26 28 29 31 34 36 38 40 42 44 47 48 50 52 54 56 58 60 62 64 66 68 70 72 74'],
       dtype=object)]

##Question 3

In [4]:
def frequences(df, patterns):
  frequencesP = np.zeros(len(patterns),dtype=float)
  for i in range(df.shape[0]):
    indexs = np.zeros(len(patterns),dtype=int)
    for j in range(df.iloc[i].count()):
      if df.iloc[i][j] == None:
        break
      for ip in range(len(patterns)):
        #print(df.iloc[i][j],patterns[ip][indexs[ip]])
        if (len(patterns[ip])!= indexs[ip] and 
            df.iloc[i][j] == patterns[ip][indexs[ip]]):
          indexs[ip] += 1
          if len(patterns[ip]) == indexs[ip]:
            frequencesP[ip] += 1.
        #print(indexs)
  for i in range(len(frequencesP)):
    frequencesP[i] = (frequencesP[i])/float(df.shape[0])
  return frequencesP

In [13]:
patterns = algoFrequences(df,10)

In [14]:
frequences(df,patterns)

array([5.11264080e-01, 8.25719650e-01, 3.12891114e-04, 3.12891114e-04,
       3.12891114e-04, 3.12891114e-04, 8.88297872e-01, 3.95181477e-01,
       4.44618273e-01, 8.94555695e-01])

In [5]:
def aire(df, patterns):
  aireP = np.zeros(len(patterns),dtype=int)
  for i in range(df.shape[0]):
    indexs = np.zeros(len(patterns),dtype=int)
    for j in range(df.iloc[i].count()):
      if df.iloc[i][j] == None:
        break
      for ip in range(len(patterns)):
        #print(df.iloc[i][j],patterns[ip][indexs[ip]])
        if (len(patterns[ip])!= indexs[ip] and 
            df.iloc[i][j] == patterns[ip][indexs[ip]]):
          indexs[ip] += 1
          if len(patterns[ip]) == indexs[ip]:
            aireP[ip] += 1
        #print(indexs)
  for i in range(len(aireP)):
    aireP[i] = aireP[i]*len(patterns[i])
  return aireP

In [16]:
patterns = algoArea(df,10)

In [18]:
aire(df,patterns)

array([   3, 2971, 5278,    3, 5718,    0,    3, 5530,    3, 2842])

## Question 4

Nous allons maintenant tester nos algorithmes avec des jeux de données suggérés dans le sujet.

In [6]:
dataset_1 = pd.read_table("https://bitbucket.org/anesbendimerad/sigibbssamplingcode/raw/6699a50508fe177ee0c00dcc7d8e5390ee53688a/ItemsetDatasets/chess.txt", sep=" ",header=None)
del dataset_1[37]
dataset_1.head()

0   1   2   3   4   5   6   7   8   9   ...  27  28  29  30  31  32  33  \
0   1   3   5   7   9  11  13  15  17  19  ...  56  58  60  62  64  66  68   
1   1   3   5   7   9  12  13  15  17  19  ...  56  58  60  62  64  66  68   
2   1   3   5   7   9  12  13  16  17  19  ...  56  58  60  62  64  66  68   
3   1   3   5   7   9  11  13  15  17  20  ...  56  58  60  62  64  66  68   
4   1   3   5   7   9  11  13  15  17  19  ...  56  58  60  62  64  66  68   

   34  35  36  
0  70  72  74  
1  70  72  74  
2  70  72  74  
3  70  72  74  
4  70  72  74  

[5 rows x 37 columns]

In [11]:
# On réalise algoFrequence sur le dataset_1 5 fois.
dsFrequence1 = algoFrequences(dataset_1, 5)
# On ressort les fréquences 
print(1)
freq1 = frequences(dataset_1, dsFrequence1)
print(2)

# On réalise algoAire sur le dataset_1.
dsArea1 = algoArea(dataset_1, 10)
print(3)
# On ressort les valeur
area1 = aire(dataset_1, dsArea1)
print(4)

1
2
3
4


In [21]:
dataset_2 = pd.read_fwf("https://www.philippe-fournier-viger.com/spmf/datasets/kosarak_sequences.txt", sep=" ",header=None,)
dataset_2 = dataset_2[0].str.split(' ', expand=True)
dataset_2.head()

0   1   2     3     4     5     6     7     8     9    ...   93    94   \
0   1  -1   2    -1     3    -1    -2  None  None  None  ...  None  None   
1   1  -1  -2  None  None  None  None  None  None  None  ...  None  None   
2   4  -1   5    -1     6    -1     7    -1    -2  None  ...  None  None   
3   1  -1   8    -1    -2  None  None  None  None  None  ...  None  None   
4   9  -1  10    -1    -2  None  None  None  None  None  ...  None  None   

    95    96    97    98    99    100   101   102  
0  None  None  None  None  None  None  None  None  
1  None  None  None  None  None  None  None  None  
2  None  None  None  None  None  None  None  None  
3  None  None  None  None  None  None  None  None  
4  None  None  None  None  None  None  None  None  

[5 rows x 103 columns]

In [ ]:
# On réalise algoFrequence sur le dataset_2 5 fois.
dsFrequence2 = algoFrequences(dataset_2, 5)
# On ressort les fréquences 
freq2 = frequences(dataset_2, dsFrequence2)

# On réalise algoAire sur le dataset_2.
dsArea2 = algoArea(dataset_2, 10)
# On ressort les valeur
area2 = aire(dataset_2, dsArea2)

In [ ]:
dataset_2.iloc[0]

0         1
1        -1
2         2
3        -1
4         3
       ... 
98     None
99     None
100    None
101    None
102    None
Name: 0, Length: 103, dtype: object

In [ ]:
dataset_2.iloc[0].dropna()

0     1
1    -1
2     2
3    -1
4     3
5    -1
6    -2
Name: 0, dtype: object

In [66]:
dataset_3 = pd.read_fwf("https://www.philippe-fournier-viger.com/spmf/datasets/MSNBC.txt", sep=" ",header=None,)
dataset_3 = dataset_3[0].str.split(' ', expand=True)
dataset_3.head() 

0   1   2   3   4   5   6   ...    50    51    52    53    54    55    56
0   6  -1   9  -1   4  -1  10  ...  None  None  None  None  None  None  None
1  13  -1   7  -1  13  -1   7  ...  None  None  None  None  None  None  None
2   1  -1   4  -1   7  -1   1  ...  None  None  None  None  None  None  None
3   9  -1   7  -1   9  -1   7  ...  None  None  None  None  None  None  None
4   4  -1  10  -1   2  -1  10  ...  None  None  None  None  None  None  None

[5 rows x 57 columns]

In [ ]:
# On réalise algoFrequence sur le dataset_3 5 fois.
dsFrequence3 = algoFrequences(dataset_3, 5)
# On ressort les fréquences 
freq3 = frequences(dataset_3, dsFrequence3)

# On réalise algoAire sur le dataset_3.
dsArea3 = algoArea(dataset_3, 10)
# On ressort les valeur
area3 = aire(dataset_3, dsArea3)

In [ ]:
dataset_4 = pd.read_fwf("https://www.philippe-fournier-viger.com/spmf/datasets/BIBLE.txt", sep=" ",header=None,)
dataset_4 = dataset_4[0].str.split(' ', expand=True)
dataset_4.shape

(36369, 175)

In [ ]:
# On réalise algoFrequence sur le dataset_4 5 fois.
dsFrequence4 = algoFrequences(dataset_4, 5)
# On ressort les fréquences 
freq4 = frequences(dataset_4, dsFrequence4)

# On réalise algoAire sur le dataset_4.
dsArea4 = algoArea(dataset_4, 10)
# On ressort les valeur
area4 = aire(dataset_4, dsArea4)

## Question 5

### Etude emprique

Nous allons étudier les dataset ci-dessus.

#### Dataset n°1

##### Algorithme de fréquence

Dans un premier temps, nous allons analyser les 5 échantillons sur la fréquence ainsi que leurs aires. 

In [12]:
print(dsFrequence1)
for f in freq1:
    print("La fréquence est de ", f*100, "%.")

[array([ 2,  3,  5,  9, 12, 14, 15, 18, 22, 23, 25, 27, 29, 31, 34, 36, 39,
       40, 42, 44, 46, 50, 54, 56, 58, 60, 62, 64, 66, 68, 71, 72, 74]), array([ 1,  3,  5,  9, 11, 14, 18, 20, 21, 25, 28, 31, 36, 38, 40, 42, 44,
       46, 54, 56, 58, 60, 62, 68, 70, 75]), array([ 2,  5,  7,  9, 11, 14, 15, 25, 27, 36, 39, 43, 44, 46, 48, 50, 54,
       56, 60, 73]), array([ 5,  9, 12, 29, 34, 36, 39, 40, 46, 48, 51, 55, 56, 58, 66, 72, 75]), array([ 7, 12, 15, 17, 23, 29, 31, 36, 39, 40, 42, 45, 46, 50, 55, 58, 62,
       71, 72, 74])]
La fréquence est de  0.03128911138923655 %.
La fréquence est de  0.0625782227784731 %.
La fréquence est de  0.03128911138923655 %.
La fréquence est de  0.4380475594493116 %.
La fréquence est de  0.18773466833541927 %.


Add some comments here

##### Algorithme de l'aire
Dans un second temps, nous allons analyser l'algorithme de l'aire.

In [13]:
print(dsArea1)
print(area1)

[array([ 3,  5, 20, 22, 23, 25, 29, 31, 46, 52, 56, 62, 64, 66, 68, 70, 72,
       74]), array([ 2,  5, 12, 16, 17, 21, 23, 25, 28, 31, 34, 50, 57, 58, 62, 64]), array([ 2,  3,  9, 18, 20, 23, 29, 34, 40, 46, 54, 56, 58, 60, 64, 69, 71,
       72, 74]), array([ 1,  7,  9, 11, 14, 17, 25, 32, 34, 36, 39, 43, 44, 52, 54, 56, 58,
       60, 62, 65]), array([ 1,  3,  5,  7,  9, 11, 13, 17, 28, 29, 31, 34, 38, 40, 42, 46, 48,
       52, 55, 58, 64, 66, 70, 75]), array([ 3,  5, 13, 15, 23, 27, 29, 31, 38, 48, 51, 52, 56, 58, 69, 72]), array([ 1,  6, 11, 14, 19, 21, 25, 31, 36, 39, 42, 48, 51, 52, 54, 56, 58,
       64, 66, 68, 75]), array([ 5,  7, 11, 13, 17, 19, 21, 25, 27, 36, 38, 43, 46, 50, 56, 73]), array([ 2,  7, 19, 21, 27, 31, 34, 40, 44, 60, 65, 69, 73, 74]), array([ 4,  5, 12, 16, 20, 24, 25, 29, 31, 36, 38, 44, 46, 50, 52, 54, 56,
       58, 62, 64, 68, 74])]
[504  32 190 280 288 368  42 176 518 242]


Add some comments here

#### Dataset n°2

##### Algorithme de fréquence 

Comme pour le dataset précédant, nous allons dans un premier temps executé l'algorithme de la fréquence et obtenir 5 échantillons. 

In [ ]:
echantillons = algoFrequences(dataset_2, 5)
print(echantillons)

Nous obtenons donc nos 5 motifs que nous allons analyser avec la fonction implémentées à la question 3.

In [ ]:
freq = frequences(dataset_2, echantillons)
for f in freq:
    print("La fréquence est de ", f, "%.")

Add some comments here

##### Algorithme de l'aire
Dans un second temps, nous allons exucter l'algorithme de la fréquence et chercher à obtenir un échantillon.

In [ ]:
echantillons = algoAire(dataset_2, 10)
print(echantillons)

Nous avons donc obtenu notre motif que nous allons analyser avec la fonction implémentées à la question 3.

In [ ]:
area = aire(dataset_2, echantillons)

Add some comments here

#### Dataset n°3

##### Algorithme de fréquence 

Comme pour le dataset précédant, nous allons dans un premier temps executé l'algorithme de la fréquence et obtenir 5 échantillons. 

In [ ]:
echantillons = algoFrequences(dataset_3, 5)
print(echantillons)

Nous obtenons donc nos 5 motifs que nous allons analyser avec la fonction implémentées à la question 3.

In [ ]:
freq = frequences(dataset_3, echantillons)
for f in freq:
    print("La fréquence est de ", f, "%.")

Add some comments here

##### Algorithme de l'aire
Dans un second temps, nous allons exucter l'algorithme de la fréquence et chercher à obtenir un échantillon.

In [ ]:
echantillons = algoAire(dataset_3, 10)
print(echantillons)

Nous avons donc obtenu notre motif que nous allons analyser avec la fonction implémentées à la question 3.

In [ ]:
area = aire(dataset_3, echantillons)

Add some comments here

#### Dataset n°4

##### Algorithme de fréquence 

Comme pour le dataset précédant, nous allons dans un premier temps executé l'algorithme de la fréquence et obtenir 5 échantillons. 

In [ ]:
echantillons = algoFrequences(dataset_4, 5)
print(echantillons)

Nous obtenons donc nos 5 motifs que nous allons analyser avec la fonction implémentées à la question 3.

In [ ]:
freq = frequences(dataset_4, echantillons)
for f in freq:
    print("La fréquence est de ", f, "%.")

Add some comments here

##### Algorithme de l'aire
Dans un second temps, nous allons exucter l'algorithme de la fréquence et chercher à obtenir un échantillon.

In [ ]:
echantillons = algoAire(dataset_4, 10)
print(echantillons)

Nous avons donc obtenu notre motif que nous allons analyser avec la fonction implémentées à la question 3.

In [ ]:
area = aire(dataset_4, echantillons)

Add some comments here

## Question 6

On a constaté que lorsque l'on avait une ligne beaucoup plus grande que les autres, les algorithmes de fréquence et d'aire favorisent la ligne la plus grande pour créer des motifs. On souhaite trouver des motifs fréquents, donc on souhaite éviter des motifs qui s'applique seulement dans des grandes lignes. Nous avons trouver trois solutions:

*   Supprimer les grandes lignes du dataset
*   Réduire la taille des grandes lignes
*   Modifier le poids accorder à la ligne la plus grande


In [ ]:
dsetGL = pd.read_fwf("https://www.philippe-fournier-viger.com/spmf/datasets/kosarak_sequences.txt", sep=" ",header=None,)
df_gl= dsetGL[0].str.split(' ', expand=True)

## Cas où le dataset est chargé dans un df
On va calculer la moyenne du nombre d'item par ligne et en fonction de cela on suprimera les colonnes supérieurs à la taille moyenne du nombre d'item/ligne
On ne regarde pas toute les lignes on en regarde que 40% (on pourras changer)

In [ ]:
df_gl.shape 

(990002, 103)

In [ ]:
def resizeDataSet(df,percentage):
  shape = df.shape
  sum = 0
  #for index, row in df.iterrows():
  for _ in range(int(shape[0]*percentage)):
    #if random.uniform(0.,100.) < 5.:
    sum += shape[1] - df.iloc[random.randint(0,shape[0]-1)].isnull().sum()
  mean = sum/(shape[0]*percentage)
  for i in range(shape[1]-1,int(mean),-1):
    del df[i]
  return df

In [ ]:
resizeDataSet(dataset_3,0.4)

0   1   2   3   4   5   6   ...    20    21    22    23    24    25    26
0       6  -1   9  -1   4  -1  10  ...  None  None  None  None  None  None  None
1      13  -1   7  -1  13  -1   7  ...    13    -1    14    -1    13    -1     7
2       1  -1   4  -1   7  -1   1  ...    -2  None  None  None  None  None  None
3       9  -1   7  -1   9  -1   7  ...    12    -1     3    -1    -2  None  None
4       4  -1  10  -1   2  -1  10  ...  None  None  None  None  None  None  None
...    ..  ..  ..  ..  ..  ..  ..  ...   ...   ...   ...   ...   ...   ...   ...
31785   9  -1  13  -1   8  -1   3  ...    -2  None  None  None  None  None  None
31786   6  -1   7  -1   6  -1   7  ...  None  None  None  None  None  None  None
31787   1  -1  12  -1   1  -1  10  ...    11    -1     4    -1     1    -1     7
31788   1  -1   2  -1  12  -1   2  ...    -2  None  None  None  None  None  None
31789  13  -1   7  -1   4  -1   7  ...     8    -1     5    -1     8    -1    -2

[31790 rows x 27 columns]

## Troisième solution
Text  a mettre richard

Dans cette troisième approche, on va faire une moyenne mobile de la valeur de poid

[Info pour blabla](https://www.educatim.fr/tq/co/Module_TQ_web/co/moyenne_glissante.html)

In [ ]:
def algoFrequencesSolutionA(df:pd.DataFrame,nb_pattern)-> tuple:
  #R:set = set()
  R = []
  IsInR = set()
  P: dict = dict()
  w = np.zeros(df[0].count())
  totalW = 0
  # set les probas
  for i in range(len(w)):
    w[i] = math.pow(2,len(df.iloc[i]))
    if i >= 2:
      w[i] = (w[i] + w[i-1] + w[i-2])/ 3
    totalW += w[i]
  
  # on selectionne 
  while len(R) < nb_pattern:
    random_row = random.uniform(0,totalW)
    # On cherche la ligne
    row = 0
    v = 0
    for i in range(len(w)):
      if  v > random_row:
        row = i - 1
        break
      v += w[i]
    # On selctionne un motif 
    pattern = np.array(df.iloc[row])
    random_v = random.randint(1, len(df.iloc[row]) - 1 )
    for i in range(len(pattern)- random_v):
      pattern = np.delete(pattern, random.randint(0, len(pattern) - 1 ))
    # On ajoute seulement les motifes non présent dans l'ensemble R
    IsInR.add(np.array2string(pattern))
    if len(IsInR) != len(R):
      R.append(pattern)
  return R