<a href="https://colab.research.google.com/github/pi-aire/dataminig_sampling/blob/main/TP_DataMining.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Échantillonnage direct de l'espace des motifs

### BRUNEAU Richard - VASLIN Pierre





In [ ]:
import numpy as np
import scipy.special as sps
import math
import matplotlib
import pandas as pd
import random

In [ ]:
# Le dataframe
df = pd.read_table("https://bitbucket.org/anesbendimerad/sigibbssamplingcode/raw/6699a50508fe177ee0c00dcc7d8e5390ee53688a/ItemsetDatasets/chess.txt", sep=" ",header=None)
del df[37]
df.head()

0   1   2   3   4   5   6   7   8   ...  28  29  30  31  32  33  34  35  36
0   1   3   5   7   9  11  13  15  17  ...  58  60  62  64  66  68  70  72  74
1   1   3   5   7   9  12  13  15  17  ...  58  60  62  64  66  68  70  72  74
2   1   3   5   7   9  12  13  16  17  ...  58  60  62  64  66  68  70  72  74
3   1   3   5   7   9  11  13  15  17  ...  58  60  62  64  66  68  70  72  74
4   1   3   5   7   9  11  13  15  17  ...  58  60  62  64  66  68  70  72  74

[5 rows x 37 columns]

In [ ]:
df = pd.read_fwf("https://bitbucket.org/anesbendimerad/sigibbssamplingcode/raw/6699a50508fe177ee0c00dcc7d8e5390ee53688a/ItemsetDatasets/chess.txt", sep="",header=None)
df.

0  1  2  3                                                  4
0     1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 34 36 38 40...
1     1  3  5  7  9 12 13 15 17 19 21 23 25 27 29 31 34 36 38 40...
2     1  3  5  7  9 12 13 16 17 19 21 23 25 27 29 31 34 36 38 40...
3     1  3  5  7  9 11 13 15 17 20 21 23 25 27 29 31 34 36 38 40...
4     1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 34 36 38 40...
...  .. .. .. ..                                                ...
3191  2  4  5  7  9 11 13 16 17 19 21 23 26 27 29 33 34 36 38 40...
3192  2  4  5  7  9 11 13 16 17 19 21 23 26 27 29 33 34 36 38 40...
3193  2  4  5  7  9 11 13 16 17 19 21 23 26 27 29 31 34 36 38 40...
3194  2  4  5  8  9 11 13 16 17 19 21 23 26 27 30 33 35 36 38 40...
3195  2  4  5  8  9 11 13 16 17 19 21 23 26 27 30 31 35 36 38 40...

[3196 rows x 5 columns]

## Question 1

In [73]:
def algoFrequences(df:pd.DataFrame,nb_pattern)-> tuple:
  #R:set = set()
  R = []
  IsInR = set()
  P: dict = dict()
  w = np.zeros(df.shape[0])
  totalW = 0
    
  # set les probas
  for i in range(len(w)):
    size = len(df.iloc[i].dropna())
    w[i] = math.pow(2,size)
    totalW += w[i]
  
  # on selectionne 
  while len(R) < nb_pattern:
    random_row = random.uniform(0,totalW)
    # On cherche la ligne
    row = 0
    v = 0
    for i in range(len(w)):
      if  v > random_row:
        row = i - 1
        break
      v += w[i]
    # On selctionne un motif 
    pattern = np.array(df.iloc[row].dropna())
    random_v = random.randint(1, len(pattern) - 1 )
    for i in range(len(pattern)- random_v):
      pattern = np.delete(pattern, random.randint(0, len(pattern) - 1 ))
    # On ajoute seulement les motifs non présent dans l'ensemble R
    IsInR.add(np.array2string(pattern))
    if len(IsInR) != len(R):
      R.append(pattern)
  return R

In [ ]:
algoFrequences(df,10)

[array([ 2,  4,  7,  9, 21, 29, 34, 38, 49, 58, 62]),
 array([ 9, 14, 20, 25, 27, 29, 32, 34, 36, 40, 46, 56, 60, 62, 64, 66, 71,
        73, 74]),
 array([ 1,  6,  8, 11, 14, 15, 17, 19, 21, 24, 25, 27, 34, 42, 44, 46, 51,
        54, 56, 58, 60, 62, 64, 66, 72]),
 array([ 2,  3,  5,  7,  9, 13, 15, 17, 19, 22, 23, 25, 28, 29, 34, 38, 40,
        42, 46, 48, 50, 52, 56, 58, 60, 62, 64, 66, 68, 70, 72, 75]),
 array([ 1, 14, 16, 17, 31, 34, 36, 50, 52, 56, 62, 64, 72]),
 array([ 1,  3,  5, 11, 14, 15, 17, 19, 22, 23, 28, 31, 34, 36, 40, 42, 45,
        46, 48, 50, 52, 55, 56, 58, 60, 62, 66, 72]),
 array([ 1,  3,  5,  7, 11, 13, 15, 17, 21, 24, 25, 27, 29, 36, 39, 44, 47,
        51, 56, 58, 60, 62, 65, 68, 71, 72, 74]),
 array([ 5,  7, 10, 12, 17, 23, 25, 29, 31, 34, 38, 40, 44, 48, 57, 60, 62,
        69, 70, 72]),
 array([20, 21, 27, 31, 34, 38, 42, 48, 51, 52, 56, 62, 66, 69, 70, 73]),
 array([ 1, 26, 34, 55, 66, 70, 75])]

## Question 2

In [ ]:
def algoArea(df:pd.DataFrame,nb_pattern)-> tuple:
  R = []
  IsInR = set()
  
  # set les probas
  w = np.zeros(df[0].count())
  totalW = 0
  for i in range(1, len(w)):
    size = len(df.iloc[i].dropna())
    w[i] = size * (2 ** (size - 1))
    totalW += w[i]
  
  # on selectionne 
  while len(R) < nb_pattern:
    # On cherche la ligne
    random_row = random.uniform(0,totalW)
    v, row = 0,0
    for i in range(len(w)):
      if v > random_row:
        row = i - 1
        break
      v += w[i]
      
    # On set les probabilités de k (taille du motif)
    # On souhaite que le sous-ensemble est une taille calculée 
    # proportionnellement avec les tailles des datarecords (ligne) 
    ks = np.zeros(len(df.iloc[row].dropna()))
    totalK = 0
    for i in range(len(ks)):
        ks[i] = sps.binom(len(ks), i + 1)
        totalK += ks[i]
    random_kp = random.uniform(0, totalK)
    # On cherche la ligne
    k, v = 0,0
    for i in range(len(ks)):
      if v > random_kp:
        k = i - 1
        break
      v += ks[i]
    
    pattern = np.array(df.iloc[row])
    for i in range(len(pattern)- k):
      pattern = np.delete(pattern, random.randint(0, len(pattern) - 1 ))
    
    # On ajoute seulement les motifs non présent dans l'ensemble R
    IsInR.add(np.array2string(pattern))
    if len(IsInR) != len(R):
      R.append(pattern)
  return R

In [ ]:
algoArea(df,10)

[array([ 1,  9, 11, 13, 15, 23, 31, 38, 42, 44, 47, 48, 52, 64, 70]),
 array([ 5,  7, 18, 22, 25, 27, 34, 36, 38, 40, 44, 46, 50, 52, 56, 70]),
 array([ 2,  3,  9, 14, 17, 19, 22, 29, 31, 34, 36, 40, 48, 54, 58, 60, 62,
        64, 66, 68]),
 array([ 1,  3,  9, 11, 15, 23, 28, 31, 34, 36, 40, 42, 48, 50, 54, 56, 62,
        64, 66, 72]),
 array([11, 14, 21, 24, 39, 40, 42, 44, 46, 52, 54, 56, 65]),
 array([ 5,  9, 11, 19, 22, 34, 38, 42, 44, 46, 52, 56, 60]),
 array([ 3,  7, 14, 15, 17, 29, 34, 39, 42, 45, 46, 51, 55, 64, 72]),
 array([ 1, 15, 21, 24, 25, 29, 32, 40, 58, 65, 73]),
 array([ 3,  7, 17, 25, 29, 34, 36, 42, 46, 50, 60, 66, 72]),
 array([ 3,  5,  7, 11, 15, 17, 20, 29, 34, 36, 56, 60, 62])]

##Question 3

In [ ]:
def frequences(df, patterns):
  frequencesP = np.zeros(len(patterns),dtype=float)
  for i in range(df.shape[0]):
    indexs = np.zeros(len(patterns),dtype=int)
    for j in range(df.iloc[i].count()):
      if df.iloc[i][j] == None:
        break
      for ip in range(len(patterns)):
        #print(df.iloc[i][j],patterns[ip][indexs[ip]])
        if (len(patterns[ip])!= indexs[ip] and 
            df.iloc[i][j] == patterns[ip][indexs[ip]]):
          indexs[ip] += 1
          if len(patterns[ip]) == indexs[ip]:
            frequencesP[ip] += 1.
        #print(indexs)
  for i in range(len(frequencesP)):
    frequencesP[i] = (frequencesP[i])/float(df.shape[0])
  return frequencesP

In [ ]:
patterns = algoFrequences(df,10)

In [ ]:
frequences(df,patterns)

array([0.01251564, 0.00375469, 0.00406758, 0.0034418 , 0.00312891,
       0.00375469, 0.00031289, 0.00031289, 0.07165207, 0.00125156])

In [ ]:
def aire(df, patterns):
  aireP = np.zeros(len(patterns),dtype=int)
  for i in range(df.shape[0]):
    indexs = np.zeros(len(patterns),dtype=int)
    for j in range(df.iloc[i].count()):
      if df.iloc[i][j] == None:
        break
      for ip in range(len(patterns)):
        #print(df.iloc[i][j],patterns[ip][indexs[ip]])
        if (len(patterns[ip])!= indexs[ip] and 
            df.iloc[i][j] == patterns[ip][indexs[ip]]):
          indexs[ip] += 1
          if len(patterns[ip]) == indexs[ip]:
            aireP[ip] += 1
        #print(indexs)
  for i in range(len(aireP)):
    aireP[i] = aireP[i]*len(patterns[i])
  return aireP

In [ ]:
patterns = algoArea(df,10)

In [ ]:
aire(df,patterns)

array([460, 480, 760,  36,  63,  16, 360, 216, 390, 648])

## Question 4

Nous allons maintenant tester nos algorithmes avec des jeux de données suggérés dans le sujet.

In [ ]:
dataset_1 = pd.read_table("https://bitbucket.org/anesbendimerad/sigibbssamplingcode/raw/6699a50508fe177ee0c00dcc7d8e5390ee53688a/ItemsetDatasets/chess.txt", sep=" ",header=None)
del dataset_1[37]
dataset_1.head()

0   1   2   3   4   5   6   7   8   ...  28  29  30  31  32  33  34  35  36
0   1   3   5   7   9  11  13  15  17  ...  58  60  62  64  66  68  70  72  74
1   1   3   5   7   9  12  13  15  17  ...  58  60  62  64  66  68  70  72  74
2   1   3   5   7   9  12  13  16  17  ...  58  60  62  64  66  68  70  72  74
3   1   3   5   7   9  11  13  15  17  ...  58  60  62  64  66  68  70  72  74
4   1   3   5   7   9  11  13  15  17  ...  58  60  62  64  66  68  70  72  74

[5 rows x 37 columns]

In [ ]:
frequences(dataset_1,algoFrequences(dataset_1,10))

array([0.00031289, 0.04192741, 0.00125156, 0.00312891, 0.01720901,
       0.00031289, 0.00031289, 0.0175219 , 0.00093867, 0.02878598])

In [ ]:
aire(dataset_1,algoArea(dataset_1,10))

array([ 154,  378,   90,  171,   30, 8625,   16,  160,  126,  486])

In [ ]:
dataset_2 = pd.read_fwf("https://www.philippe-fournier-viger.com/spmf/datasets/kosarak_sequences.txt", sep=" ",header=None,)
dataset_2 = dataset_2[0].str.split(' ', expand=True)
dataset_2.head()

0   1   2     3     4     5     6    ...   96    97    98    99    100   101   102
0   1  -1   2    -1     3    -1    -2  ...  None  None  None  None  None  None  None
1   1  -1  -2  None  None  None  None  ...  None  None  None  None  None  None  None
2   4  -1   5    -1     6    -1     7  ...  None  None  None  None  None  None  None
3   1  -1   8    -1    -2  None  None  ...  None  None  None  None  None  None  None
4   9  -1  10    -1    -2  None  None  ...  None  None  None  None  None  None  None

[5 rows x 103 columns]

In [ ]:
dataset_2.iloc[0]

0         1
1        -1
2         2
3        -1
4         3
       ... 
98     None
99     None
100    None
101    None
102    None
Name: 0, Length: 103, dtype: object

In [ ]:
dataset_2.iloc[0].dropna()

0     1
1    -1
2     2
3    -1
4     3
5    -1
6    -2
Name: 0, dtype: object

In [ ]:
frequences(dataset_2, algoFrenquences(dataset_2, 10))

In [ ]:
aire(dataset_2, algoArea(dataset_2, 10))

In [66]:
dataset_3 = pd.read_fwf("https://www.philippe-fournier-viger.com/spmf/datasets/MSNBC.txt", sep=" ",header=None,)
dataset_3 = dataset_3[0].str.split(' ', expand=True)
dataset_3.head() 

0   1   2   3   4   5   6   ...    50    51    52    53    54    55    56
0   6  -1   9  -1   4  -1  10  ...  None  None  None  None  None  None  None
1  13  -1   7  -1  13  -1   7  ...  None  None  None  None  None  None  None
2   1  -1   4  -1   7  -1   1  ...  None  None  None  None  None  None  None
3   9  -1   7  -1   9  -1   7  ...  None  None  None  None  None  None  None
4   4  -1  10  -1   2  -1  10  ...  None  None  None  None  None  None  None

[5 rows x 57 columns]

In [ ]:
frequences(dataset_3, algoFrequences(dataset_3, 10))

In [ ]:
aire(dataset_3, algoArea(dataset_3,10))

array([   0,   31,   28,   27, 1917,   21,    0,  196, 1248,   31])

In [ ]:
dataset_4 = pd.read_fwf("https://www.philippe-fournier-viger.com/spmf/datasets/BIBLE.txt", sep=" ",header=None,)
dataset_4 = dataset_4[0].str.split(' ', expand=True)
dataset_4.shape

(36369, 175)

In [ ]:
frequences(dataset_4, algoFrequences(dataset_4, 10))

In [ ]:
aire(dataset_4, algoArea(dataset_4,10))

## Question 5

### Etude emprique

Nous allons étudier les dataset ci-dessus.

### Dataset n°1

#### Algorithme de fréquence


Dans un premier temps, nous allons executer l'algorithme de la fréquence et chercher à obtenir 5 échantillons.

In [ ]:
echantillons = algoFrequences(dataset_1, 5)
print(echantillons)

[array([ 5, 12, 14, 15, 19, 21, 23, 25, 29, 34, 36, 38, 44, 46, 48, 50, 52,
       56, 58, 60, 62, 64, 66, 68, 70, 72]), array([11, 36]), array([ 5, 11, 23, 31, 34, 46, 48, 52, 66, 71, 75]), array([ 2,  3,  7,  9, 11, 13, 15, 17, 20, 21, 24, 29, 31, 34, 36, 38, 40,
       43, 47, 48, 51, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 74]), array([ 2,  5, 17, 25, 29, 33, 34, 38, 40, 42, 44, 52, 58, 60, 62, 66, 72])]


Nous obtenons donc nos 5 motifs que nous allons analyser avec la fonction implémentées à la question 3

In [ ]:
frequences(dataset_1, algoFrequences(dataset_1, 5))

array([0.0491239 , 0.00093867, 0.00813517, 0.06007509, 0.00062578])

## Question 6

On a constaté que lorsque l'on avait une ligne beaucoup plus grande que les autres, les algorithmes de fréquence et d'aire favorisent la ligne la plus grande pour créer des motifs. On souhaite trouver des motifs fréquents, donc on souhaite éviter des motifs qui s'applique seulement dans des grandes lignes. Nous avons trouver trois solutions:

*   Supprimer les grandes lignes du dataset
*   Réduire la taille des grandes lignes
*   Modifier le poids accorder à la ligne la plus grande


In [ ]:
dsetGL = pd.read_fwf("https://www.philippe-fournier-viger.com/spmf/datasets/kosarak_sequences.txt", sep=" ",header=None,)
df_gl= dsetGL[0].str.split(' ', expand=True)

## Cas où le dataset est chargé dans un df
On va calculer la moyenne du nombre d'item par ligne et en fonction de cela on suprimera les colonnes supérieurs à la taille moyenne du nombre d'item/ligne
On ne regarde pas toute les lignes on en regarde que 40% (on pourras changer)

In [ ]:
df_gl.shape 

(990002, 103)

In [ ]:
def resizeDataSet(df,percentage):
  shape = df.shape
  sum = 0
  #for index, row in df.iterrows():
  for _ in range(int(shape[0]*percentage)):
    #if random.uniform(0.,100.) < 5.:
    sum += shape[1] - df.iloc[random.randint(0,shape[0]-1)].isnull().sum()
  mean = sum/(shape[0]*percentage)
  for i in range(shape[1]-1,int(mean),-1):
    del df[i]
  return df

In [ ]:
resizeDataSet(dataset_3,0.4)

0   1   2   3   4   5   6   ...    20    21    22    23    24    25    26
0       6  -1   9  -1   4  -1  10  ...  None  None  None  None  None  None  None
1      13  -1   7  -1  13  -1   7  ...    13    -1    14    -1    13    -1     7
2       1  -1   4  -1   7  -1   1  ...    -2  None  None  None  None  None  None
3       9  -1   7  -1   9  -1   7  ...    12    -1     3    -1    -2  None  None
4       4  -1  10  -1   2  -1  10  ...  None  None  None  None  None  None  None
...    ..  ..  ..  ..  ..  ..  ..  ...   ...   ...   ...   ...   ...   ...   ...
31785   9  -1  13  -1   8  -1   3  ...    -2  None  None  None  None  None  None
31786   6  -1   7  -1   6  -1   7  ...  None  None  None  None  None  None  None
31787   1  -1  12  -1   1  -1  10  ...    11    -1     4    -1     1    -1     7
31788   1  -1   2  -1  12  -1   2  ...    -2  None  None  None  None  None  None
31789  13  -1   7  -1   4  -1   7  ...     8    -1     5    -1     8    -1    -2

[31790 rows x 27 columns]

## Troisième solution
Text  a mettre richard

Dans cette troisième approche, on va faire une moyenne mobile de la valeur de poid

[Info pour blabla](https://www.educatim.fr/tq/co/Module_TQ_web/co/moyenne_glissante.html)

In [ ]:
def algoFrequencesSolutionA(df:pd.DataFrame,nb_pattern)-> tuple:
  #R:set = set()
  R = []
  IsInR = set()
  P: dict = dict()
  w = np.zeros(df[0].count())
  totalW = 0
  # set les probas
  for i in range(len(w)):
    w[i] = math.pow(2,len(df.iloc[i]))
    if i >= 2:
      w[i] = (w[i] + w[i-1] + w[i-2])/ 3
    totalW += w[i]
  
  # on selectionne 
  while len(R) < nb_pattern:
    random_row = random.uniform(0,totalW)
    # On cherche la ligne
    row = 0
    v = 0
    for i in range(len(w)):
      if  v > random_row:
        row = i - 1
        break
      v += w[i]
    # On selctionne un motif 
    pattern = np.array(df.iloc[row])
    random_v = random.randint(1, len(df.iloc[row]) - 1 )
    for i in range(len(pattern)- random_v):
      pattern = np.delete(pattern, random.randint(0, len(pattern) - 1 ))
    # On ajoute seulement les motifes non présent dans l'ensemble R
    IsInR.add(np.array2string(pattern))
    if len(IsInR) != len(R):
      R.append(pattern)
  return R